# Generated by Django 2.2.13 on 2020-06-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'F'), ('M', 'M')], max_length=1, null=True),
        ),
    ]
